### ISSUE TITLE
Ensure that WP5 needs are recorded in the Overall Product Backlog

### ISSUE THREAD

**Issue by jastram** [openETCS/demonstrator#15]
As @srieger pointed out in https://github.com/openETCS/toolchain/issues/389 , we need  to ensure that WP7 is recognized as a stakeholder with respect to the Demonstrator.  Our job is to support WP5.

The best way to ensure that is to create and maintain WP5-specific product backlog items in the overall product backlog.

I will now go ahead and close our WP7 issue.

**Comment by mahlmann** [comment]
WP5 specific items/issues have been integrated in the product backlog. If there is further need for coordination I propose to raise this topic in the next product backlog grooming session or to make use of the  issue tracker in the product backlog repository.
