### ISSUE TITLE
D5.1 approbation

### ISSUE THREAD

**Issue by mahlmann** [openETCS/demonstrator#16]
Dear @Nicolas-VanLandeghem 

can you please clarify the state of D5.1 and check with the technical assessor and quality assessor (Ainhoa Gracia) if they are going to sign the document in its current version?

If so, I kindly ask you to start the signature process.

**Comment by idelatorre** [comment]
Dear @Nicolas-VanLandeghem , dear @mahlmann

After the reception of the D5.1 WP5 Demostrator - Functional Specifications document and its revision, the document has been signed. We will wait some days to see the decision of the issue commented in issue #17 to deliver both or only one.

**Comment by Nicolas-VanLandeghem** [comment]
Dear @idelatorre , dear @mahlmann 

thank you for your review. I commented issue #17 for shipment details.

**Comment by mahlmann** [comment]
Signed deliverable has been received. Thanks!
