### ISSUE TITLE
M5.1 approbation

### ISSUE THREAD

**Issue by mahlmann** [openETCS/demonstrator#17]
Dear @Nicolas-VanLandeghem 

I have a short remark concerning M5.1: The document is classified as confidential currently. Since the document resides in a public repository, I assume the classification has been done unintentionally.

Moreover, can you please clarify the state of M5.1 and check with the technical assessor and quality assessor ( Ainhoa Gracia ) if they are going to sign the document in its current version?

If so, I kindly ask you to start the signature process.

**Comment by Nicolas-VanLandeghem** [comment]
Dear @idelatorre , dear @mahlmann 

thank you very much for your review and your comments. Maybe it would be easier you sign both documents (D5.1 + M5.1) and send them back to us. Thus, I would forward both to the DB after I updated the M5.1 following your remarks.
By the way, I suggest I integrate your remarks somewhere during this afternoon and push them on the gitHub. Once you agree on the M5.1 update, you can proceed with shipment.

Hope it is okay for you.
Best regards,
Nicolas

**Comment by Nicolas-VanLandeghem** [comment]
Dear @idelatorre 

I pushed an updated version of the M5.1 document.

Best regards,
Nicolas

**Comment by idelatorre** [comment]
The errors regarding to strange symbols are fixed, and the reference to GUI in the mode/level manager in section 2.2 (page 7 line 7) is removed. However, the reference to GUI in the data manager of section 2.2 (page 6 line 20) and in the figure 3 still appears and in section 9 there is not information about this. See images
![figure 3 section2_2](https://cloud.githubusercontent.com/assets/3976065/5701954/748d8112-9a53-11e4-8a39-61c69e95c682.png)
![section 9](https://cloud.githubusercontent.com/assets/3976065/5701955/748e3bca-9a53-11e4-8841-fda6940e361a.png)
![section2_2 page6](https://cloud.githubusercontent.com/assets/3976065/5701956/748fbbc6-9a53-11e4-914d-2e3c0150ccb9.png)

**Comment by idelatorre** [comment]
Sorry, it is only not mentioned in the exchange data sections. In the overview it is mentioned as User interface instead of GUI

**Comment by Nicolas-VanLandeghem** [comment]
I updated the document accordingly. It was indeed forgotten. 
Best regards.

**Comment by idelatorre** [comment]
Dear @Nicolas-VanLandeghem , dear @mahlmann 

Both documents (D5.1 + M5.1) have been signed and sent them back to ERSA.

Please let me know if you do not receive them.

Best regards

Izaskun

**Comment by mahlmann** [comment]
@idelatorre
Thanks a lot for the review and signing the documents!

@Nicolas-VanLandeghem 
Please forward the signed documents to DB in Munich when you received them.

**Comment by Nicolas-VanLandeghem** [comment]
Dear Izaskun @idelatorre,

we just received both signed documents. Thanks a lot for their review. Thank you also for having printed out the updated version of M5.1 !

Both documents are now on the way to Munich. Peter @mahlmann should get them in the upcoming days.

Best regards.

**Comment by mahlmann** [comment]
Signed deliverable has been received. Thanks!
