### ISSUE TITLE
M5.3 Approbation

### ISSUE THREAD

**Issue by idelatorre** [openETCS/demonstrator#18]
Dear @Nicolas-VanLandeghem , dear @mahlmann 

After the reception of the M5.3 ESP Basic Installation and User Guide and M5.3 Automatic Test Runner User manual documents and their revision, the first document has been signed and in the second it has been detected that there is no content in the table of contents and figures and tables sections. Please, it is necessary to include this information to make easy the search.

**Comment by mahlmann** [comment]
Thanks for your feedback @idelatorre 

@didierersa :
Since @Nicolas-VanLandeghem not available anymore can you please update M5.3 according to the review comments of @idelatorre ?

**Comment by didierersa** [comment]
I will make the requested change ASAP. Thank you for reporting.

@idelatorre , Should I send you the fixed "paper" documents back or shouldI just fix it on github ?

**Comment by didierersa** [comment]
@idelatorre , I've committed the fixed document, is this enough for your side ?

**Comment by idelatorre** [comment]
Yes. The document has been signed. I will send you today both M5.3 ESP Basic Installation and User Guide and M5.3 Automatic Test Runner User manual documents as you can sign the last one and then you can send the documents to DB.

**Comment by didierersa** [comment]
Thank you very much.

De : idelatorre [mailto:notifications@github.com]
Envoyé : lundi 23 mars 2015 10:09
À : openETCS/demonstrator
Cc : Didier WECKMANN
Objet : Re: [demonstrator] M5.3 Approbation (#18)


Yes. The document has been signed. I will send you today both M5.3 ESP Basic Installation and User Guide and M5.3 Automatic Test Runner User manual documents as you can sign the last one and then you can send the documents to DB.

**Comment by mahlmann** [comment]
Signed deliverable has been received. Thanks!
