### ISSUE TITLE
US-Definition of GE TCP+CPU

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/demonstrator#26]

**Comment by darioGE** [comment]
Committed document (https://github.com/openETCS/demonstrator/commit/5aa888e08b2fcb09529b60f1120e0d04639a5e6d).   @BaseliyosJacob is this enough to close the issue?

**Comment by MarcBehrens** [comment]
I will close the issue due to the documentation being provided.
If you need more documentation @BaseliyosJacob, please reopen the issue.
