### ISSUE TITLE
US-Definition of GE TCP+CPU+ODO+Balise Channel

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/demonstrator#28]

**Comment by MarcBehrens** [comment]
ODO function and BTM functionality are currently out of scope of openETCS

**Comment by darioGE** [comment]
Committed document (https://github.com/openETCS/demonstrator/commit/5aa888e08b2fcb09529b60f1120e0d04639a5e6d).   @BaseliyosJacob is this enough to close the issue?

**Comment by BaseliyosJacob** [comment]
o.k.!! This is enough for me!! Can be closed
