### ISSUE TITLE
US-System Architecture definition of ERSA + GE + openETCS System

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/demonstrator#32]

**Comment by MarcBehrens** [comment]
A basic documentation of the GE Hardware Configuration: BRD + COM + DGN + CPU will be provided by @darioge

**Comment by BaseliyosJacob** [comment]
Hello Dario and Marc,

is it possible to get a full overview about the Architecture together with the ERSA Environment + openETCS Model and GE Hardware?

Thank you very much

**Comment by darioGE** [comment]
GE HW Platform has been described (see https://github.com/openETCS/demonstrator/commit/5aa888e08b2fcb09529b60f1120e0d04639a5e6d).  This should be enough to permit @MarcBehrens to move on with the full architecture overview, shouldn't it?
